### ISSUE TITLE
2015-04-24: cms-a-frameworky-nad-nette

### ISSUE THREAD

**Issue by paveljanda** [contributte/planette-site#26] opened 2017-07-16 12:00 UTC
Nette Framework umožňuje příjemnou tvorbu vlastního frameworku či CMS, které dalším způsobem obohacují a rozšiřují jeho použitelnost.

Tato díla jsou obvykle volně šiřitelná, proto mohou poskytnout podobné usnadnění práce jako Nette samotné.

### CMS

|---
| Název | Autor | Demo | Zdroj | Fórum | Rok* | verze Nette | DB Layer
|---
| **[Flame:CMS](http://projects.jsifalda.name/flame/**) | [sifik](user:5153) | [demo](http://flame.jsifalda.name/) | [github](https://github.com/flame-cms/cms) | -- | 2012 | dev-master | Doctrine 2 ORM
| **Moe's CMS** | [davidM](user:2459) | [demo](http://demo.moes.cz/) | [github](https://github.com/davidmoravek/moes-cms) | [vlákno](http://forum.nette.org/cs/10190-moe-s-cms-redakcni-system-postaveny-na-nette) | 2012 | 2.0-dev | Doctrine 2 ORM
| **NanoCMS** | [Droid](user:3772) | [demo](http://www.gnip.cz/nanocms/www/) | [download](http://www.gnip.cz/nanocms/www/nanocms.zip), [github](https://github.com/Ginny/NanoCMS) | [vlákno](http://forum.nette.org/cs/7700-nanocms-nette-example-dynamickeho-webu) | 2011 | 2.0-dev | Nette\Database
| **[nPress](http://www.npress.info/**) | [Pavel Zbytovský](user:136) | [demo](http://demo.npress.info/) | [download](https://github.com/downloads/zbycz/npress/npress-v0.5-rc.zip), [github](https://github.com/zbycz/npress) | [vlákno](http://forum.nette.org/cs/9973-npress-dalsi-cms-na-nette) | 2012 | 2.0 | dibi
| **[CoolMS](http://coolms.slamecka.cz/**) | [Ondřej Slámečka](user:2604) | [demo](http://coolms.slamecka.cz/) | [github](https://github.com/OndrejSlamecka/CoolMS) | [vlákno](http://forum.nette.org/cs/9190-coolms-web-content-management-system-zalozeny-na-nette) | 2011 | 2.0 | Nette\Database
| **[Venne:CMS](https://github.com/Venne/cms-module**|) [pepakriz](user:2465) | [demo](http://demo.venne.cz/) | [github](https://github.com/Venne/cms-module)| [vlákno](http://forum.nette.org/cs/8154-venne-cms-volne-cms-pro-nette) | 2012 | 2.0-dev | Doctrine 2 ORM
| **[WebCMS2](https://github.com/ufik/WebCMS2**|) [Tomas Voslar] | [demo](http://demo.webcook.cz/) | [github](https://github.com/ufik/WebCMS2)| -- | 2014 | 2.0.* | Doctrine 2 ORM

### Frameworky

|---
| Název | Autor | Zdroj | Fórum | Rok* | verze Nette | DB Layer
|---
| **[Flame](http://projects.jsifalda.name/flame/**) | [sifik](user:5153) | [github](https://github.com/flame-org/Framework) | - | 2012 | 2.1-dev | Doctrine 2 ORM
| **[Nella](http://nellafw.org/**) | [Patrik Votoček](user:1639) | [github](https://github.com/nella/framework) | - | 2006 | 2.0 | Doctrine 2 ORM
| **Neuron** | [HonzaMarek](user:516) |[github](https://github.com/janmarek/Neuron) | - | 2010 | ? | Doctrine
| **[Lohini](http://lohini.net**) | [Lopo](user:2108) | [github](https://github.com/Lohini/framework) | - | 2010 | 2.0-dev | Doctrine
| **[Venne:FW](https://github.com/Venne/framework**|) [pepakriz](user:2465) | [github](https://github.com/Venne/framework) | -- | 2012 | 2.0-dev | --

### Balíky rozšíření

|---
| Název | Maintainer | Zdroj | Fórum
|---
| **[Kdyby](http://kdyby.org/)** | [Filip Procházka](user:2118) | [github](https://github.com/Kdyby) | [vlastní fórum](https://help.kdyby.org/)
| **[Nextras](http://nextras.cz/)** | [Hrach](user:449), [Jan Tvrdík](user:1657) | [github](https://github.com/nextras) | -
| **[Zenify](https://github.com/zenify)** | [Tomáš Votruba](user:3194) | [github](https://github.com/zenify) | -

**Comment by paveljanda** [comment] 2017-07-16 12:00
author: chemix (iamchemix@gmail.com)

**Comment by meridius** [comment] 2017-07-30 20:40
this is a duplicate of #60

**Closed as completed** 2017-07-30 20:46 UTC
Labels: Status: Translation Needed
